//#define NO_FREE_INIT


#define USE_REQUEST_LIST_SWITCH
#define USE_REQUEST_LIST_FREE_PGD
#define USE_REQUEST_LIST_NEW_PGD
#define USE_REQUEST_LIST_SET_PMD
#define USE_REQUEST_LIST_SET_PTE


//#define NO_RM_EX_FROM_1TO1
//#define NO_EXCEPT_EMU
#define MONITOR_ENABLED

